// create payable

PATCH http://localhost:3000/integrations/assignor/049551eb-ca20-4c8d-acf7-38675649efc2

Content-Type: application/json

{
  "document": "13276542706",
  "email": "teste@teste.com",
  "phone": "984863437",
  "name": "Gabriel Muniz Ferreira" 
}

GET  http://localhost:3000/integrations/payable

{
  "value": 135.50,
  "emissionDate": "2020-04-09T00:00:00.000Z",
  "assignorId": "049551eb-ca20-4c8d-acf7-38675649efc2"
}
